In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPool2D,Dropout,Flatten
from keras.datasets  import mnist
from keras.utils import np_utils
from sklearn import metrics
import numpy as np
#import pandas as pd
import tensorflow

In [21]:
#prepprocessing
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()
print(xtrain.shape,'\t',ytrain.shape)
xtrain=xtrain.reshape(xtrain.shape[0],xtrain.shape[1],xtrain.shape[2],1).astype('float32')
xtest=xtest.reshape(xtest.shape[0],28,28,1).astype('float32')
print(xtrain.shape,xtest.shape)

ytrain=np_utils.to_categorical(ytrain)
test=ytest.copy()
ytest=np_utils.to_categorical(ytest)
print(ytrain.shape,ytest.shape)


(60000, 28, 28) 	 (60000,)
(60000, 28, 28, 1) (10000, 28, 28, 1)
(60000, 10) (10000, 10)


In [28]:
#making architecture
model=Sequential()
model.add(Conv2D(32,(5,5),input_shape=(28,28,1),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(.2))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(ytest.shape[1],activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(xtrain,ytrain,batch_size=500,epochs=10,verbose=2)


Epoch 1/10
120/120 - 14s - loss: 4.9077 - accuracy: 0.8107
Epoch 2/10
120/120 - 14s - loss: 0.2141 - accuracy: 0.9420
Epoch 3/10
120/120 - 15s - loss: 0.1317 - accuracy: 0.9629
Epoch 4/10
120/120 - 16s - loss: 0.0915 - accuracy: 0.9735
Epoch 5/10
120/120 - 15s - loss: 0.0730 - accuracy: 0.9778
Epoch 6/10
120/120 - 17s - loss: 0.0573 - accuracy: 0.9823
Epoch 7/10
120/120 - 16s - loss: 0.0487 - accuracy: 0.9844
Epoch 8/10
120/120 - 16s - loss: 0.0404 - accuracy: 0.9870
Epoch 9/10
120/120 - 16s - loss: 0.0337 - accuracy: 0.9895
Epoch 10/10
120/120 - 16s - loss: 0.0292 - accuracy: 0.9909


In [29]:
#testing and prediction
ypred=model.predict(xtest)
ypred=np.argmax(ypred,axis=1)
#print("predictions\n",ypred)
print("accuracy\n",metrics.accuracy_score(test,ypred))
print(metrics.confusion_matrix(test,ypred))
print("classification report\n",metrics.classification_report(test,ypred))

accuracy
 0.983
[[ 969    0    2    0    0    0    4    1    3    1]
 [   0 1126    2    0    0    2    2    0    3    0]
 [   2    2 1018    1    1    0    2    4    2    0]
 [   0    0    1 1001    0    3    0    1    2    2]
 [   0    1    4    0  961    0    1    1    3   11]
 [   2    0    0    6    0  878    3    0    2    1]
 [   2    2    1    0    2    3  947    0    1    0]
 [   0    5   11    1    2    0    0 1003    2    4]
 [   9    0    3    1    3    9    0    2  944    3]
 [   0    5    0    4    6    5    0    2    4  983]]
classification report
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.99      0.98      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.98      0.98       982
           5       0.98      0.98      0.98       892
           6       0.99      0.99      0.99       9